namespace Calendar.Application.Businesses.UpdateBusinessDetails;

public sealed record UpdateBusinessDetailsResult(
    bool Succeeded,
    UpdateBusinessDetailsError Error,
    Guid? BusinessId,
    string? Name,
    string? Slug,
    string? Category,
    string? Description,
    string? ContactEmail,
    string? ContactPhoneNumber,
    string? WebsiteUrl,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? PostalCode,
    string? CountryCode,
    string? TimeZoneId,
    string? CurrencyCode,
    int? MaxAdvanceBookingDays)
{
    public static UpdateBusinessDetailsResult Success(
        Guid businessId,
        string name,
        string slug,
        string? category,
        string? description,
        string? contactEmail,
        string? contactPhoneNumber,
        string? websiteUrl,
        string? addressLine1,
        string? addressLine2,
        string? city,
        string? postalCode,
        string? countryCode,
        string timeZoneId,
        string currencyCode,
        int maxAdvanceBookingDays) => new(
            true,
            UpdateBusinessDetailsError.None,
            businessId,
            name,
            slug,
            category,
            description,
            contactEmail,
            contactPhoneNumber,
            websiteUrl,
            addressLine1,
            addressLine2,
            city,
            postalCode,
            countryCode,
            timeZoneId,
            currencyCode,
            maxAdvanceBookingDays);

    public static UpdateBusinessDetailsResult Failure(UpdateBusinessDetailsError error) => new(
        false,
        error,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
}
