using Calendar.Application.Abstractions.Messaging;
using Calendar.Application.Appointments.CancelAdminAppointment;
using Calendar.Application.Appointments.CancelCustomerAppointment;
using Calendar.Application.Appointments.CreateAppointment;
using Calendar.Application.Appointments.GetAppointmentDetails;
using Calendar.Application.Appointments.ListAdminAppointments;
using Calendar.Application.Appointments.ListCustomerAppointments;
using Calendar.Application.Appointments.Scheduling;
using Calendar.Application.Appointments.UpdateAppointmentInternalNotes;
using Calendar.Application.Appointments.UpdateAppointmentStatus;
using Calendar.Application.Auth.LoginAdmin;
using Calendar.Application.Auth.LoginCustomer;
using Calendar.Application.Auth.RegisterBusiness;
using Calendar.Application.Auth.RegisterCustomer;
using Calendar.Application.Availability;
using Calendar.Application.Businesses;
using Calendar.Application.Businesses.UpdateBusinessBookingWindow;
using Calendar.Application.Businesses.UpdateBusinessDetails;
using Calendar.Application.Services;
using Calendar.Application.Services.CreateService;
using Calendar.Application.Services.DeleteService;
using Calendar.Application.Services.UpdateService;
using Calendar.Application.Services.UpdateServiceActiveState;
using Calendar.Application.StaffMemberAvailabilities;
using Calendar.Application.StaffMemberAvailabilities.CreateStaffMemberAvailability;
using Calendar.Application.StaffMemberAvailabilities.DeleteStaffMemberAvailability;
using Calendar.Application.StaffMemberAvailabilities.ListStaffMemberAvailabilities;
using Calendar.Application.StaffMemberAvailabilities.UpdateStaffMemberAvailability;
using Calendar.Application.StaffMemberAvailabilityExceptions;
using Calendar.Application.StaffMemberAvailabilityExceptions.CreateStaffMemberAvailabilityException;
using Calendar.Application.StaffMemberAvailabilityExceptions.DeleteStaffMemberAvailabilityException;
using Calendar.Application.StaffMemberAvailabilityExceptions.ListStaffMemberAvailabilityExceptions;
using Calendar.Application.StaffMemberAvailabilityExceptions.UpdateStaffMemberAvailabilityException;
using Calendar.Application.StaffMemberServices;
using Calendar.Application.StaffMemberServices.AssignStaffMemberService;
using Calendar.Application.StaffMemberServices.UnassignStaffMemberService;
using Calendar.Application.StaffMemberServices.UpdateStaffMemberServiceActiveState;
using Calendar.Application.StaffMembers;
using Calendar.Application.StaffMembers.CreateStaffMember;
using Calendar.Application.StaffMembers.DeleteStaffMember;
using Calendar.Application.StaffMembers.UpdateStaffMember;
using Calendar.Application.StaffMembers.UpdateStaffMemberActiveState;
using Microsoft.Extensions.DependencyInjection;

namespace Calendar.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<ICommandHandler<LoginAdminCommand, LoginAdminResult>, LoginAdminCommandHandler>();
        services.AddScoped<ICommandHandler<LoginCustomerCommand, LoginCustomerResult>, LoginCustomerCommandHandler>();
        services.AddScoped<ICommandHandler<RegisterBusinessCommand, RegisterBusinessResult>, RegisterBusinessCommandHandler>();
        services.AddScoped<ICommandHandler<RegisterCustomerCommand, RegisterCustomerResult>, RegisterCustomerCommandHandler>();
        services.AddScoped<ICommandHandler<CreateAppointmentCommand, CreateAppointmentResult>, CreateAppointmentCommandHandler>();
        services.AddScoped<ICommandHandler<CancelAdminAppointmentCommand, CancelAdminAppointmentResult>, CancelAdminAppointmentCommandHandler>();
        services.AddScoped<ICommandHandler<CancelCustomerAppointmentCommand, CancelCustomerAppointmentResult>, CancelCustomerAppointmentCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateAppointmentStatusCommand, UpdateAppointmentStatusResult>, UpdateAppointmentStatusCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateAppointmentInternalNotesCommand, UpdateAppointmentInternalNotesResult>, UpdateAppointmentInternalNotesCommandHandler>();
        services.AddScoped<IQueryHandler<GetAppointmentDetailsQuery, AppointmentDetails?>, GetAppointmentDetailsQueryHandler>();
        services.AddScoped<IQueryHandler<ListAdminAppointmentsQuery, ListAdminAppointmentsResult>, ListAdminAppointmentsQueryHandler>();
        services.AddScoped<IQueryHandler<ListCustomerAppointmentsQuery, IReadOnlyList<AppointmentDetails>>, ListCustomerAppointmentsQueryHandler>();
        services.AddScoped<IAppointmentScheduleValidator, AppointmentScheduleValidator>();
        services.AddScoped<IQueryHandler<ListAvailableSlotsQuery, ListAvailableSlotsResult>, ListAvailableSlotsQueryHandler>();
        services.AddScoped<ICommandHandler<CreateServiceCommand, CreateServiceResult>, CreateServiceCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateServiceCommand, UpdateServiceResult>, UpdateServiceCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateServiceActiveStateCommand, UpdateServiceActiveStateResult>, UpdateServiceActiveStateCommandHandler>();
        services.AddScoped<ICommandHandler<DeleteServiceCommand, DeleteServiceResult>, DeleteServiceCommandHandler>();
        services.AddScoped<ICommandHandler<CreateStaffMemberCommand, CreateStaffMemberResult>, CreateStaffMemberCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateStaffMemberCommand, UpdateStaffMemberResult>, UpdateStaffMemberCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateStaffMemberActiveStateCommand, UpdateStaffMemberActiveStateResult>, UpdateStaffMemberActiveStateCommandHandler>();
        services.AddScoped<ICommandHandler<DeleteStaffMemberCommand, DeleteStaffMemberResult>, DeleteStaffMemberCommandHandler>();
        services.AddScoped<ICommandHandler<AssignStaffMemberServiceCommand, AssignStaffMemberServiceResult>, AssignStaffMemberServiceCommandHandler>();
        services.AddScoped<ICommandHandler<UnassignStaffMemberServiceCommand, UnassignStaffMemberServiceResult>, UnassignStaffMemberServiceCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateStaffMemberServiceActiveStateCommand, UpdateStaffMemberServiceActiveStateResult>, UpdateStaffMemberServiceActiveStateCommandHandler>();
        services.AddScoped<IQueryHandler<ListStaffMemberServiceAssignmentsByStaffMemberQuery, ListStaffMemberServiceAssignmentsResult>, AdminStaffMemberServiceAssignmentQueryHandler>();
        services.AddScoped<IQueryHandler<ListStaffMemberServiceAssignmentsByServiceQuery, ListStaffMemberServiceAssignmentsResult>, AdminStaffMemberServiceAssignmentQueryHandler>();
        services.AddScoped<ICommandHandler<CreateStaffMemberAvailabilityCommand, CreateStaffMemberAvailabilityResult>, CreateStaffMemberAvailabilityCommandHandler>();
        services.AddScoped<IQueryHandler<ListStaffMemberAvailabilitiesQuery, ListStaffMemberAvailabilitiesResult>, ListStaffMemberAvailabilitiesQueryHandler>();
        services.AddScoped<ICommandHandler<UpdateStaffMemberAvailabilityCommand, UpdateStaffMemberAvailabilityResult>, UpdateStaffMemberAvailabilityCommandHandler>();
        services.AddScoped<ICommandHandler<DeleteStaffMemberAvailabilityCommand, DeleteStaffMemberAvailabilityResult>, DeleteStaffMemberAvailabilityCommandHandler>();
        services.AddScoped<ICommandHandler<CreateStaffMemberAvailabilityExceptionCommand, CreateStaffMemberAvailabilityExceptionResult>, CreateStaffMemberAvailabilityExceptionCommandHandler>();
        services.AddScoped<IQueryHandler<ListStaffMemberAvailabilityExceptionsQuery, ListStaffMemberAvailabilityExceptionsResult>, ListStaffMemberAvailabilityExceptionsQueryHandler>();
        services.AddScoped<ICommandHandler<UpdateStaffMemberAvailabilityExceptionCommand, UpdateStaffMemberAvailabilityExceptionResult>, UpdateStaffMemberAvailabilityExceptionCommandHandler>();
        services.AddScoped<ICommandHandler<DeleteStaffMemberAvailabilityExceptionCommand, DeleteStaffMemberAvailabilityExceptionResult>, DeleteStaffMemberAvailabilityExceptionCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateBusinessDetailsCommand, UpdateBusinessDetailsResult>, UpdateBusinessDetailsCommandHandler>();
        services.AddScoped<ICommandHandler<UpdateBusinessBookingWindowCommand, UpdateBusinessBookingWindowResult>, UpdateBusinessBookingWindowCommandHandler>();
        services.AddScoped<IQueryHandler<GetBusinessByIdQuery, BusinessDetails?>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<GetBusinessProfileByIdQuery, BusinessProfileDetails?>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<GetBusinessProfileBySlugQuery, BusinessProfileDetails?>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<ListBusinessServicesQuery, ListBusinessServicesResult>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<GetBusinessServiceQuery, BusinessServiceDetails?>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<ListBusinessStaffMembersQuery, ListBusinessStaffMembersResult>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<GetBusinessStaffMemberQuery, BusinessStaffMemberDetails?>, PublicBusinessQueryHandler>();
        services.AddScoped<IQueryHandler<ListAdminServicesQuery, ListAdminServicesResult>, AdminServiceQueryHandler>();
        services.AddScoped<IQueryHandler<GetAdminServiceQuery, GetAdminServiceResult>, AdminServiceQueryHandler>();
        services.AddScoped<IQueryHandler<ListAdminStaffMembersQuery, ListAdminStaffMembersResult>, AdminStaffMemberQueryHandler>();
        services.AddScoped<IQueryHandler<GetAdminStaffMemberQuery, GetAdminStaffMemberResult>, AdminStaffMemberQueryHandler>();

        return services;
    }
}
