namespace Calendar.Application.Appointments.CreateAppointment;

public sealed record CreateAppointmentResult(
    bool Succeeded,
    CreateAppointmentError Error,
    Guid? AppointmentId,
    Guid? BusinessId,
    Guid? StaffMemberId,
    Guid? ServiceId,
    Guid? CustomerId,
    DateTimeOffset? StartAtUtc,
    DateTimeOffset? EndAtUtc,
    string? Status,
    string? CustomerNotes,
    string? ServiceNameSnapshot,
    int? ServiceDurationMinutesSnapshot,
    decimal? PriceAmountSnapshot,
    string? CurrencyCodeSnapshot,
    DateTimeOffset? CreatedAtUtc)
{
    public static CreateAppointmentResult Success(
        Guid appointmentId,
        Guid businessId,
        Guid staffMemberId,
        Guid serviceId,
        Guid customerId,
        DateTimeOffset startAtUtc,
        DateTimeOffset endAtUtc,
        string status,
        string? customerNotes,
        string serviceNameSnapshot,
        int serviceDurationMinutesSnapshot,
        decimal priceAmountSnapshot,
        string currencyCodeSnapshot,
        DateTimeOffset createdAtUtc) => new(
            true,
            CreateAppointmentError.None,
            appointmentId,
            businessId,
            staffMemberId,
            serviceId,
            customerId,
            startAtUtc,
            endAtUtc,
            status,
            customerNotes,
            serviceNameSnapshot,
            serviceDurationMinutesSnapshot,
            priceAmountSnapshot,
            currencyCodeSnapshot,
            createdAtUtc);

    public static CreateAppointmentResult Failure(CreateAppointmentError error) => new(
        false,
        error,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
}
