export const routes = {
  home: '/',
  search: '/search',
  businessProfile: (slug: string) => `/b/${slug}`,
  appointmentSlotFlow: (slug: string) => `/b/${slug}/appointment`,
  appointmentDetail: (appointmentId: string) => `/appointments/${appointmentId}`,
  customerAppointments: '/customer/appointments',
  customerLogin: '/auth/customer/login',
  customerRegister: '/auth/customer/register',
  adminLogin: '/auth/admin/login',
  businessRegister: '/auth/business/register',
  adminDashboard: '/admin',
  adminBusinessSettings: '/admin/business-settings',
  adminServices: '/admin/services',
  adminStaffMembers: '/admin/staff-members',
  adminAvailability: '/admin/availability',
  adminAppointments: '/admin/appointments',
} as const;
